### ISSUE TITLE
AS 2.3 Support

### ISSUE THREAD

**Issue by TheExDeus** [BlindMindStudios/AngelScript-JIT-Compiler#18]
AngelScript 2.30 released yesterday changed the CallSystemFunction signature. Previously it was
```
int CallSystemFunction(int id, asCContext *context, void *objectPointer);
```
Now it is:
```
int CallSystemFunction(int id, asCContext *context);
```
It is used only twice in JIT, but it uses the object pointer argument (in one case, it's nullptr in the other), so I'm not sure what needs replacing.

**Comment by ThyReaper** [comment]
We're currently finishing up the release of our studio's game, so we may not have time to update to the newest AS and update the JIT for several weeks.

**Comment by zordtk** [comment]
any update on this?

**Comment by audioboy77** [comment]
It would be helpful to know if this project is in active development and whether you still plan to update to Angelscript 2.3.  We would like to use AngelScript over Lua, but the option to have a jit compiler is an important part of the decision.  Thanks.

**Comment by TheExDeus** [comment]
I don't think it would be that hard to fix as it is only really used once. I am not that intimate with the JIT source yet to dwell on it. When I have more free time I will try to fix it myself, as I am also interested in using AS JIT.
